### ISSUE TITLE
Right arrow landscape issue

### ISSUE THREAD

**Issue by khaledannajar** [camelcc/MenuPopOverView#3]
Scenario: 
1- open the menu in landscape mode in iPhone with options count enough to show right and left arrows.
2- tap on the right arrow button.
3- try to tap again on the left arrow button

Expected:
show again the first options

Actual
the left arrow  button does not respond

![](http://i.giphy.com/26BGRb5eDDBGJiX9C.gif)

**Comment by camelcc** [comment]
After I update the lib, can not reproduce. Note that now the bounds change needs to be managed outside.
Please report this issue if you can reproduce it.
